export const mockProducts = [
  {
    id: '1',
    sku: 'KUR-001',
    name: "Women's Cotton Kurta",
    category: 'Fashion',
    subCategory: 'Kurtas & Suits',
    costPrice: 450,
    masterPrice: 999,
    channelPrices: { amazon: 1049, flipkart: 999, myntra: 1099, website: 999, pos: 950 },
    stock: 245,
    status: 'Active',
    channels: ['amazon', 'flipkart', 'myntra', 'website', 'pos'],
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=400&q=80',
    description: 'Elegant ethnic cotton kurta with soft breathable fabric and stylish traditional print.',
    brand: 'Bhartiye Crafts',
    gender: 'Women',
    material: 'Cotton',
    color: 'Blue',
    fit: 'Regular',
    sold: 245,
    revenue: 367550,
  },
  {
    id: '2',
    sku: 'BAM-002',
    name: 'Handcrafted Bamboo Basket',
    category: 'Home Decor',
    subCategory: 'Storage & Organization',
    costPrice: 280,
    masterPrice: 699,
    channelPrices: { amazon: 749, flipkart: 699, myntra: 829, website: 699, pos: 650 },
    stock: 186,
    status: 'Active',
    channels: ['amazon', 'flipkart', 'website', 'pos'],
    image: 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=400&q=80',
    description: 'Handcrafted eco-friendly bamboo basket suitable for home storage, organizing, and gifting.',
    brand: 'Bhartiye Crafts',
    material: 'Bamboo',
    color: 'Natural Brown',
    sold: 186,
    revenue: 167400,
  },
  {
    id: '3',
    sku: 'SHIRT-003',
    name: "Men's Casual Shirt",
    category: 'Fashion',
    subCategory: 'Tops & Shirts',
    costPrice: 320,
    masterPrice: 799,
    channelPrices: { amazon: 849, flipkart: 799, myntra: 899, website: 799, pos: 720 },
    stock: 42,
    status: 'Low Stock',
    channels: ['amazon', 'flipkart', 'myntra', 'website', 'pos'],
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=400&q=80',
    description: '100% premium cotton casual slim-fit shirt for everyday wear.',
    brand: 'Urban Style',
    gender: 'Men',
    material: 'Cotton',
    color: 'Light Blue',
    sold: 142,
    revenue: 113580,
  },
  {
    id: '4',
    sku: 'DUP-004',
    name: 'Ethnic Dupatta',
    category: 'Fashion',
    subCategory: 'Dupattas',
    costPrice: 200,
    masterPrice: 499,
    channelPrices: { amazon: 549, flipkart: 499, myntra: 529, website: 499, pos: 450 },
    stock: 320,
    status: 'Active',
    channels: ['amazon', 'flipkart', 'myntra'],
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80',
    description: 'Vibrant silk blend printed ethnic dupatta with border detailing.',
    brand: 'Bhartiye Crafts',
    gender: 'Women',
    material: 'Silk Blend',
    color: 'Red/Gold',
    sold: 128,
    revenue: 89600,
  },
  {
    id: '5',
    sku: 'SHOE-001',
    name: "Men's Running Shoes",
    category: 'Footwear',
    subCategory: 'Sports Shoes',
    costPrice: 1200,
    masterPrice: 2499,
    channelPrices: { amazon: 2799, flipkart: 2499, myntra: 2599, website: 2499, pos: 2300 },
    stock: 18,
    status: 'Low Stock',
    channels: ['amazon', 'flipkart', 'myntra', 'website', 'pos'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80',
    description: 'Lightweight cushioned breathable running shoes designed for high performance.',
    brand: 'AeroSport',
    gender: 'Men',
    material: 'Mesh/Rubber',
    color: 'Red/Black',
    sold: 420,
    revenue: 249800,
  }
];

export const mockOrders = [
  {
    id: '#ORD7821',
    customer: 'Sneha Verma',
    channel: 'Amazon',
    amount: 1299,
    status: 'Delivered',
    date: '28 Sep, 10:24',
    items: [{ name: "Women's Cotton Kurta", qty: 1, price: 1299 }],
    paymentMethod: 'UPI',
  },
  {
    id: '#ORD7820',
    customer: 'Rohit Kumar',
    channel: 'Flipkart',
    amount: 2499,
    status: 'Shipped',
    date: '28 Sep, 09:12',
    items: [{ name: "Men's Running Shoes", qty: 1, price: 2499 }],
    paymentMethod: 'Card',
  },
  {
    id: '#ORD7819',
    customer: 'Anjali Singh',
    channel: 'Website',
    amount: 899,
    status: 'Processing',
    date: '27 Sep, 20:45',
    items: [{ name: 'Handcrafted Bamboo Basket', qty: 1, price: 899 }],
    paymentMethod: 'UPI',
  },
  {
    id: '#ORD7818',
    customer: 'Karan Mehta',
    channel: 'Myntra',
    amount: 3299,
    status: 'Delivered',
    date: '27 Sep, 18:30',
    items: [{ name: "Men's Casual Shirt", qty: 2, price: 1649 }],
    paymentMethod: 'Net Banking',
  },
  {
    id: '#ORD7817',
    customer: 'Priya Sharma',
    channel: 'Offline',
    amount: 1150,
    status: 'Completed',
    date: '27 Sep, 16:20',
    items: [{ name: 'Ethnic Dupatta', qty: 2, price: 575 }],
    paymentMethod: 'Cash',
  }
];

export const mockCustomers = [
  {
    id: 'CUST-01',
    name: 'Rahul Kumar',
    email: 'rahul@gmail.com',
    phone: '+91 98765 43210',
    location: 'Delhi, India',
    totalOrders: 12,
    totalSpent: 8450,
    avgOrderValue: 704,
    lastOrder: '20 Sep 2026',
    status: 'Active',
    type: 'Regular',
    loyaltyPoints: 856
  },
  {
    id: 'CUST-02',
    name: 'Sneha Sharma',
    email: 'sneha@gmail.com',
    phone: '+91 98765 43211',
    location: 'Mumbai, India',
    totalOrders: 8,
    totalSpent: 12390,
    avgOrderValue: 1549,
    lastOrder: '18 Sep 2026',
    status: 'Active',
    type: 'Premium',
    loyaltyPoints: 1240
  },
  {
    id: 'CUST-03',
    name: 'Amit Verma',
    email: 'amit@gmail.com',
    phone: '+91 98765 43212',
    location: 'Bangalore, India',
    totalOrders: 25,
    totalSpent: 24990,
    avgOrderValue: 999,
    lastOrder: '17 Sep 2026',
    status: 'Active',
    type: 'VIP',
    loyaltyPoints: 3420
  }
];

export const mockReturns = [
  {
    rma: 'RMA1001',
    orderId: '#AMZ78210',
    customer: 'Aarav Sharma',
    product: "Men's Running Shoes (Size 9, Black)",
    channel: 'Amazon',
    amount: 2499,
    reason: 'Size issue (too tight)',
    status: 'In Transit',
    refundStatus: 'Pending',
    date: '20 Sep 2026'
  },
  {
    rma: 'RMA1002',
    orderId: '#FLP67211',
    customer: 'Sneha Patel',
    product: "Women's Kurta (M, Blue)",
    channel: 'Flipkart',
    amount: 899,
    reason: 'Product not as described',
    status: 'Awaiting Inspection',
    refundStatus: 'Pending',
    date: '19 Sep 2026'
  }
];

export const mockChannels = [
  { id: 'amazon', name: 'Amazon', status: 'Not Connected', products: 0, orders: 0, sync: 'Not Connected', color: 'bg-amber-500' },
  { id: 'flipkart', name: 'Flipkart', status: 'Not Connected', products: 0, orders: 0, sync: 'Not Connected', color: 'bg-blue-500' },
  { id: 'myntra', name: 'Myntra', status: 'Not Connected', products: 0, orders: 0, sync: 'Not Connected', color: 'bg-pink-500' },
  { id: 'website', name: 'Own Website', status: 'Not Connected', products: 0, orders: 0, sync: 'Not Connected', color: 'bg-indigo-500' },
  { id: 'pos', name: 'POS / Offline Store', status: 'Not Connected', products: 0, orders: 0, sync: 'Not Connected', color: 'bg-emerald-500' },
];

export const mockNotifications = [
  { id: 1, title: 'New order received', text: 'Order #ORD001245 from Amit Kumar', category: 'Orders', channel: 'Website', time: '10 min ago', priority: 'High', unread: true },
  { id: 2, title: 'Low stock alert', text: "Men's Running Shoes (SKU: SHOE-001) has only 18 items remaining", category: 'Inventory', channel: '-', time: '2 hours ago', priority: 'Medium', unread: true },
  { id: 3, title: 'Return request received', text: 'Return request for Order #ORD001198', category: 'Returns', channel: 'Amazon', time: '3 hours ago', priority: 'Medium', unread: true },
  { id: 4, title: 'Amazon sync completed', text: 'Successfully synced 245 products', category: 'Channels', channel: 'Amazon', time: '5 hours ago', priority: 'Low', unread: false },
];
